routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'AuthController@index')->name('auth.login');
Route::post('login', 'AuthController@login')->name('atuh.login');

Route::group(['middleware' => ['role:all']], function () {
    Route::get('/', 'DashboardController@index');
    Route::get('logout', 'AuthController@logout')->name('auth.logout');
    Route::post('cari', 'DashboardController@cariData')->name('organization.cari');
    Route::get('info_bar', 'DashboardController@infoBar')->name('info_bar');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password/update', 'ProfileController@updatePassword')->name('update.password');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('profile', 'profileController');
    Route::get('organization/datatables', 'OrganizationController@datatables')->name('organization.datatables');
    Route::resource('organization', 'OrganizationController');
    Route::resource('manager', 'ManagerController');
    Route::group(['middleware' => ['role:admin,manager']], function () {
        Route::get('users/datatables', 'UsersController@datatables')->name('users.datatables');
        Route::resource('users', 'UsersController');
    });
});

app/Models/Organization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    use HasFactory;

    protected $table = 'organization';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'name', 'email', 'phone', 'logo', 'website', 'active', 'manager_id'
    ];

    public static function laratablesCustomAction($organization)
    {
        return view('backoffice.organization.action', compact('organization'))->render();
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function manager()
    {
        return $this->belongsTo(User::class, 'manager_id');
    }
}

app/Http/Controllers/OrganizationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Organization;
use App\Models\User;
use App\Http\Requests\Backoffice\OrganizationGet;
use App\Http\Requests\Backoffice\OrganizationStore;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Support\Facades\DB;
use App\Http\Services\UploadServices;

class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        return view('backoffice.organization.index', [
            "title" => 'List organization',
            "menu"  => 'organization',
            "user"  => $user,
        ]);
    }

    public function datatables(Request $request)
    {
        return Laratables::recordsOf(Organization::class, function ($query) use ($request) {
            if($request->type == 'manager') {
                return $query->select('organization.*')
                        ->where('manager_id', $request->manager_id);
            } else {
                return $query->select('organization.*');
            }
            
        });
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = Auth::user();
        if($user->role != 'admin') {
            return redirect()->back()->with('message_error', 'user not have access');
        }
        return view('backoffice.organization.form', [
            "title"            => "Tambah organization",
            "menu"             => "organization",
            "action"           => "create",
            "organization"     => new Organization(),
            "manager"          => User::where('role', 'manager')->get(),
            "user"  => $user,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrganizationStore $request)
    {
        DB::beginTransaction();
        try {
            $organization = new Organization();
            $file  = new UploadServices();
            $logo = $file->uploadSingleFile($request->logo, 'img/backoffice/logo');
            $organization->fill($request->all());
            $organization->user_id = Auth::user()->id;
            if (!empty($logo)) {
                $organization->logo = $logo;
            }
            $organization->save();
            DB::commit();
            return redirect()->route('organization.show', $organization->id)->with('message_success', 'success add organization');
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->back()->with('message_error', 'failed add organization ' . $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('backoffice.organization.show', [
            "title"            => "Detail Organization",
            "menu"             => "organization",
            "action"           => "show",
            "organization"     => Organization::find($id),
            "user"             => Auth::user(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backoffice.organization.form', [
            "title"            => "Edit organization",
            "menu"             => "organization",
            "action"           => "edit",
            "organization"     => Organization::find($id),
            "user"          => Auth::user()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrganizationStore $request, $id)
    {
        DB::beginTransaction();
        try {
            $organization = Organization::find($id);
            if($organization->manager_id != Auth::user()->id) {
                return redirect()->back()->with('message_error', 'user not have access');
            }
            $file  = new UploadServices();
            $logo = $file->uploadSingleFile($request->logo, 'img/backoffice/logo');
            $organization->fill($request->all());
            if (!empty($logo)) {
                $organization->logo = $logo;
            }
            $organization->update();
            DB::commit();
            return redirect()->route('organization.show', $organization->id)->with('message_success', 'success add organization ');
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->back()->with('message_error', 'failed add organization ' . $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organization = Organization::find($id);
        $user = Auth::user();
        if($user->role != 'admin') {
            if($organization->manager_id != $user->id) {
                return redirect()->back()->with('message_error', 'not have access ');
            }
        }
        $organization->active = '0';
        $organization->update();

        return redirect()->back()->with('message_success', 'success delete/deactive organization');
    }
}

resources/views/backoffice/organization/action.blade.php
<form action="{{ route('organization.destroy', $organization->id) }}" method="post">
    @csrf
    @method('DELETE')
    <a href="{{ route('organization.edit', $organization->id) }}" class="btn btn-secondary btn-sm edit-data">
        Edit
    </a>
     <a href="{{ route('organization.show', $organization->id) }}" class="btn btn-info btn-sm edit-data">
        Detail
    </a>
    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Hapus data ini ?')">Hapus</button>
    
</form>

resources/views/backoffice/organization/form.blade.php
@extends('backoffice.layouts.app')
@section('css')

@endsection
@section('content')
<div class="content-wrapper" style="min-height: 180px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $title }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Manager</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card  card-primary">
                    <div class="card-header" style="background-color: #09aaaf">
                        <h3 class="card-title">{{ $title }}</h3>
                    </div>
                      @if (session('message_success'))
                            <div class="alert alert-success">
                                {{ session('message_success') }}
                            </div>
                    @endif
                    @if($errors->any())
                        {{ implode('', $errors->all('<div>:message</div>')) }}
                    @endif
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                        @if (session('message_success'))
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ session('message_success') }}
                        </div>
                        @endif
                        <form method="POST" action="{{ $action == 'create' ? route('organization.store') : route('organization.update', $organization->id) }}"
                            enctype="multipart/form-data">
                            @csrf
                            @if($action == 'edit')
                            @method('PUT')
                            @endif
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputNama">Nama</label>
                                        <input type="hidden" value="{{ $action  }}" name="action" />
                                        <input type="hidden" value="{{ $menu  }}" name="role"/>
                                        <input type="text" class="form-control @error('name') is-invalid @enderror"
                                            placeholder="Nama" name="name" value="{{ old('name', $organization->name) }}">
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputPhone">Nomor Hp</label>
                                        <input type="phone" class="form-control @error('phone') is-invalid @enderror"
                                            placeholder="nomor telepon" name="phone"
                                            value="{{ old('phone', $organization->phone) }}">
                                        @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputEmail">Email</label>
                                        <input type="email" class="form-control @error('email') is-invalid @enderror"
                                            placeholder="Email" name="email" value="{{ old('email', $organization->email) }}">
                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                               <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputEmail">Logo</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Upload</span>
                                            </div>
                                            <div class="custom-file">
                                                <input type="file"
                                                    class="custom-file-input @error('logo') is-invalid @enderror"
                                                    id="inputGroupFile01" name="logo">
                                                <label class="custom-file-label" for="inputGroupFile01">Choose
                                                    file</label>
                                            </div>
                                            @error('logo')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputPhone">website</label>
                                        <input type="text" class="form-control @error('password') is-invalid @enderror"
                                            placeholder="website" name="website"
                                            value="{{ old('email', $organization->website) }}">
                                        @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                 @if($action == 'create')
                                 <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputPhone">Manager</label>
                                       <select class="form-control @error('jenkel') is-invalid @enderror" name="manager_id">
                                          @foreach($manager as $data)
                                            <option value="{{ $data->id }}">
                                               {{ $data->name }}
                                            </option>
                                            @endforeach
                                        </select>
                                        @error('manager_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                  @endif
                                @if($action == 'edit')
                                  <div class="col-md-6">
                                    <div class="form-group">
                                        <img src="{{ !empty($organization->logo) ? $organization->logo : 'https://via.placeholder.com/150' }}"
                                            alt="" class="img-thumbnail" width="150">
                                        @error('logo')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>  
                                @endif
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary" name="button_submit">Simpan</button>
                                    <a href="" class="btn btn-danger">Batal</a>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
@endsection
@section('js')
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
<script>
    $(document).ready(function () {
        bsCustomFileInput.init();
    });
</script>

<script type="text/javascript">
    $('#customFile').change(function(){
        let file = $(this).val().split('.');
        let cn   = file.length;

        if(file[cn-1] != 'jpg' && file[cn-1] != 'png' && file[cn-1] != 'jpeg'){
            alert('type file upload tidak di ijinkan, type file harus .jpg/jpeg/png');
            $(this).val('');
        }
    });
</script>
@endsection

resources/views/backoffice/organization/index.blade.php
@extends('backoffice.layouts.app')
@section('css')
<link href="{{ asset('storage/assets/backoffice/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $title }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"> Manager</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card ">
                        <div class="card-header">
                            <h3 class="card-title">{{ $title }}</h3>
                        </div>
                        <div class="form-group" style="margin-top: 10px">
                            <div class="col-sm-10">
                                @if($user->role == 'admin')
                                <a href="{{ route('organization.create') }}" class="btn btn-primary">Tambah
                                    Data Organizaation</a>
                                @endif
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if (session('message_success'))
                            <div class="alert alert-success">
                                {{ session('message_success') }}
                            </div>
                            @endif
                            @if (session('message_error'))
                            <div class="alert alert-error">
                                {{ session('message_error') }}
                            </div>
                            @endif
                            <table id="dataTable" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Manager</th>
                                        <th>Logo</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
<!-- /.content -->
@endsection
@section('js')
<script src="{{ asset('storage/assets/backoffice/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('storage/assets/backoffice/js/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    //function OnEditing button
    function OnEditing() {
        $("table#dataTable > tbody > tr > td > form").delegate('a.edit-data', 'click', function() {
        var elemt = $(this).closest('table#dataTable');
        var pages = elemt.DataTable().page.info().page
        localStorage.setItem('my_page', pages);
        return true;
        });
    }
    var type = '{{ $user->role }}';
    var user_id = '{{ $user->id }}';

    $('#dataTable').DataTable({
        serverSide: true,
        processing: true,
        responsive: true,
        ajax: "{{ route('organization.datatables') }}" + '?type='+type+'&manager_id='+user_id,
        "drawCallback": function(settings) {
        //create sesi on button
        OnEditing()
        },
        columns: [
            { name: 'id', searchable: false },
            { name: 'name', },
            { name: 'email', },
            { name: 'phone', },
            { name: 'manager.name'},
            { name: 'logo' },
            { name: 'action', orderable: false, searchable: false }
        ],
        columnDefs : [
         {
            targets: 0,
            orderable: true,
            render: function ( data, type, row, meta ){
            return meta.row + meta.settings._iDisplayStart + 1;
         }
         },
         {
            targets : 5,
            orderable : true,
            render: function ( data, type, row, meta ) {
            if( data == "" || data == null) {
            return "<img src='https://via.placeholder.com/150'>";
            } else {
            return "<img src='"+data+"' width='150'>";
            }
            },
            },
        ],
    });

    if(localStorage.getItem('my_page') != '') {
        var elemt = $('table#dataTable').DataTable();
        elemt.ajax.reload(function() {
        var pages = parseInt(localStorage.getItem('my_page'));
        setTimeout(function() {
        elemt.page((!pages?0:pages)).draw('page')
        setTimeout(function() {
        //hapus sesi
        localStorage.removeItem('my_page')
        }, 3000)
        }, 0) // default 0
        });

      //  return true;
    }
</script>

@endsection