routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'AuthController@index')->name('auth.login');
Route::post('login', 'AuthController@login')->name('atuh.login');

Route::group(['middleware' => ['role:all']], function () {
    Route::get('/', 'DashboardController@index');
    Route::get('logout', 'AuthController@logout')->name('auth.logout');
    Route::post('cari', 'DashboardController@cariData')->name('organization.cari');
    Route::get('info_bar', 'DashboardController@infoBar')->name('info_bar');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password/update', 'ProfileController@updatePassword')->name('update.password');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('profile', 'profileController');
    Route::get('organization/datatables', 'OrganizationController@datatables')->name('organization.datatables');
    Route::resource('organization', 'OrganizationController');
    Route::resource('manager', 'ManagerController');
    Route::group(['middleware' => ['role:admin,manager']], function () {
        Route::get('users/datatables', 'UsersController@datatables')->name('users.datatables');
        Route::resource('users', 'UsersController');
    });
});

resources/views/backoffice/pic/action.blade.php
<form action="{{ route('users.destroy', $user->id) }}" method="post">
    @csrf
    @method('DELETE')
    <a href="{{ route('users.edit', $user->id) }}" class="btn btn-secondary btn-sm edit-data">
        Edit
    </a>
    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Hapus data ini ?')">Hapus</button>
</form>

resources/views/backoffice/pic/form.blade.php
@extends('backoffice.layouts.app')
@section('css')

@endsection
@section('content')
<div class="content-wrapper" style="min-height: 180px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $title }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">PIC</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card  card-primary">
                    <div class="card-header" style="background-color: #09aaaf">
                        <h3 class="card-title">{{ $title }}</h3>
                    </div>
                      @if (session('message_success'))
                            <div class="alert alert-success">
                                {{ session('message_success') }}
                            </div>
                    @endif
                    @if($errors->any())
                        {{ implode('', $errors->all('<div>:message</div>')) }}
                    @endif
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                        @if (session('message_success'))
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ session('message_success') }}
                        </div>
                        @endif
                        <form method="POST" action="{{ $action == 'create' ? route('users.store') : route('users.update', $user_data->id) }}"
                            enctype="multipart/form-data">
                            @csrf
                            @if($action == 'edit')
                            @method('PUT')
                            @endif
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputNama">Nama</label>
                                        <input type="hidden" value="{{ $organization_id }}" name="organization_id">
                                        <input type="hidden" value="{{ $menu }}" name="role">
                                        <input type="hidden" value="{{ $action }}" name="action">
                                        <input type="text" class="form-control @error('name') is-invalid @enderror"
                                            placeholder="Nama" name="name" value="{{ old('name', $user_data->name) }}">
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputPhone">Nomor Hp</label>
                                        <input type="phone" class="form-control @error('phone') is-invalid @enderror"
                                            placeholder="nomor telepon" name="phone"
                                            value="{{ old('phone', $user_data->phone) }}">
                                        @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputEmail">Email</label>
                                        <input type="email" class="form-control @error('email') is-invalid @enderror"
                                            placeholder="Email" name="email" value="{{ old('email', $user_data->email) }}">
                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                               <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="inputEmail">Avatar</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Upload</span>
                                            </div>
                                            <div class="custom-file">
                                                <input type="file"
                                                    class="custom-file-input @error('avatar') is-invalid @enderror"
                                                    id="inputGroupFile01" name="avatar">
                                                <label class="custom-file-label" for="inputGroupFile01">Choose
                                                    file</label>
                                            </div>
                                            @error('avatar')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                @if($action == 'edit')
                                 <div class="col-md-6">
                                    <div class="form-group">
                                        <img src="{{ !empty($user_data->avatar) ? $user_data->avatar : 'https://via.placeholder.com/150' }}"
                                            alt="" class="img-thumbnail" width="150">
                                        @error('avatar')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary" name="button_submit">Simpan</button>
                                    <a href="" class="btn btn-danger">Batal</a>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
@endsection
@section('js')
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
<script>
    $(document).ready(function () {
        bsCustomFileInput.init();
    });
</script>

<script type="text/javascript">
    $('#customFile').change(function(){
        let file = $(this).val().split('.');
        let cn   = file.length;

        if(file[cn-1] != 'jpg' && file[cn-1] != 'png' && file[cn-1] != 'jpeg'){
            alert('type file upload tidak di ijinkan, type file harus .jpg/jpeg/png');
            $(this).val('');
        }
    });
</script>
@endsection

resources/views/backoffice/pic/index.blade.php
@extends('backoffice.layouts.app')
@section('css')
<link href="{{ asset('storage/assets/backoffice/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ $title }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"> Manager</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card ">
                        <div class="card-header">
                            <h3 class="card-title">{{ $title }}</h3>
                        </div>
                        <div class="form-group" style="margin-top: 10px">
                            <div class="col-sm-10">
                                <a href="{{ route('users.create', 'type=manager') }}" class="btn btn-primary">Tambah
                                    Data Manager</a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if (session('message_success'))
                            <div class="alert alert-success">
                                {{ session('message_success') }}
                            </div>
                            @endif
                            @if (session('message_error'))
                            <div class="alert alert-error">
                                {{ session('message_error') }}
                            </div>
                            @endif
                            <table id="dataTable" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Avatar</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
<!-- /.content -->
@endsection
@section('js')
<script src="{{ asset('storage/assets/backoffice/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('storage/assets/backoffice/js/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    //function OnEditing button
    function OnEditing() {
        $("table#dataTable > tbody > tr > td > form").delegate('a.edit-data', 'click', function() {
        var elemt = $(this).closest('table#dataTable');
        var pages = elemt.DataTable().page.info().page
        localStorage.setItem('my_page', pages);

        return true;
        });
    }
    $('#dataTable').DataTable({
        serverSide: true,
        processing: true,
        responsive: true,
        ajax: "{{ route('users.datatables', 'type=manager') }}",
        "drawCallback": function(settings) {
        //create sesi on button
        OnEditing()
        },
        columns: [
            { name: 'id', searchable: false },
            { name: 'name', },
            { name: 'email', },
            { name: 'active', },
            { name: 'avatar' },
            { name: 'action', orderable: false, searchable: false }
        ],
        columnDefs : [
         {
            targets: 0,
            orderable: true,
            render: function ( data, type, row, meta ){
            return meta.row + meta.settings._iDisplayStart + 1;
         }
         },
         {
            targets : 4,
            orderable : true,
            render: function ( data, type, row, meta ) {
            if( data == "" || data == null) {
            return "<img src='https://via.placeholder.com/150'>";
            } else {
            return "<img src='"+data+"' width='150'>";
            }
            },
            },
        ],
    });

    if(localStorage.getItem('my_page') != '') {
        var elemt = $('table#dataTable').DataTable();
        elemt.ajax.reload(function() {
        var pages = parseInt(localStorage.getItem('my_page'));
        setTimeout(function() {
        elemt.page((!pages?0:pages)).draw('page')
        setTimeout(function() {
        //hapus sesi
        localStorage.removeItem('my_page')
        }, 3000)
        }, 0) // default 0
        });

      //  return true;
    }
</script>

@endsection