routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'AuthController@index')->name('auth.login');
Route::post('login', 'AuthController@login')->name('atuh.login');

Route::group(['middleware' => ['role:all']], function () {
    Route::get('/', 'DashboardController@index');
    Route::get('logout', 'AuthController@logout')->name('auth.logout');
    Route::post('cari', 'DashboardController@cariData')->name('organization.cari');
    Route::get('info_bar', 'DashboardController@infoBar')->name('info_bar');
    Route::get('password', 'ProfileController@password')->name('profile.password');
    Route::put('password/update', 'ProfileController@updatePassword')->name('update.password');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('profile', 'profileController');
    Route::get('organization/datatables', 'OrganizationController@datatables')->name('organization.datatables');
    Route::resource('organization', 'OrganizationController');
    Route::resource('manager', 'ManagerController');
    Route::group(['middleware' => ['role:admin,manager']], function () {
        Route::get('users/datatables', 'UsersController@datatables')->name('users.datatables');
        Route::resource('users', 'UsersController');
    });
});

resources/views/backoffice/menu/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Copyright &copy; {{ date('Y') }}<a href="#"> Organization</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        {{-- <b>Version</b> 3.1.0-pre --}}
    </div>
</footer>
</div>

resources/views/backoffice/menu/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        {{-- <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li> --}}
    </ul>

    <!-- SEARCH FORM -->
    {{-- <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form> --}}

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown" hidden>
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="https://www.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png"
                            alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Pengaturan</span>
                <div class="dropdown-divider"></div>
                <a href="{{ route('users.index') }}" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i> profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('auth.logout') }}" class="dropdown-item">
                    <i class="fas fa-key mr-2"></i> log-out
                </a>
                <div class="dropdown-divider"></div>
            </div>
        </li>
    </ul>
</nav>

resources/views/backoffice/menu/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color : #03a1a0">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link" style="background-color : #03a1a0">
        <img src="{{ url('storage/assets/backoffice/img/logo.png')  }}" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Printerous</span>
    </a>
    <!-- Sidebar -->
    <div
        class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-transition">
        <div class="os-resize-observer-host observed">
            <div class="os-resize-observer" style="left: 0px; right: auto;"></div>
        </div>
        <div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;">
            <div class="os-resize-observer"></div>
        </div>
        <div class="os-content-glue" style="margin: 0px -8px; width: 249px; height: 100px;"></div>
        <div class="os-padding">
            <div class="os-viewport os-viewport-native-scrollbars-invisible" style="overflow-y: scroll;">
                <div class="os-content" style="padding: 0px 8px; height: 100%; width: 100%;">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="{{ $user->avatar }}"
                                class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">{{ $user->role }}</a>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                            data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                            <li class="nav-item">
                                <a href="{{ url('/') }}" class="nav-link {{ $menu == 'home' ? 'active' : '' }}">
                                    <i class="nav-icon fas fa-home"></i>
                                    <p>
                                        Dashboard
                                        {{-- <i class="right fas fa-angle-left"></i> --}}
                                    </p>
                                </a>
                            </li>
                            <li class="nav-header">PENGATURAN</li>
                            <li class="nav-item {{ $menu == 'profile' ? 'menu-open' : '' }}">
                                <a href="#" class="nav-link {{ $menu == 'profile' ? 'active' : '' }}">
                                    <i class="nav-icon fas fa-user"></i>
                                    <p>
                                        Profile
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ route('profile.index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Data Profile</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ route('profile.password') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Update Password</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        {{-- <li class="nav-header">MEMBER</li>
                           <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Member
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('backoffice.member.index') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Member Aktif</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('backoffice.member.index') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Member Register</p>
                                    </a>
                                </li>
                            </ul>
                        </li> --}}
                         <li class="nav-header">DATA</li>
                            <li class="nav-item {{ $menu == 'struktur' ? 'menu-open' : '' }}">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-id-card-alt"></i>
                                    <p>
                                       Organization
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ route('organization.index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>List Organization</p>
                                        </a>
                                    </li>
                                    @if($user->role == 'admin')
                                     <li class="nav-item">
                                        <a href="{{ route('organization.create') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Daftar Organization</p>
                                        </a>
                                    </li>
                                    @endif
                                </ul>
                            </li>
                            @if($user->role == 'admin')
                                <li class="nav-item">
                                    <a href="{{ route('users.index', 'type=manager') }}" class="nav-link">
                                        <i class="nav-icon fas fa-users"></i>
                                        <p>Manager</p>
                                    </a>
                                </li>
                            @endif
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
        </div>
        <div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);"></div>
            </div>
        </div>
        <div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="height: 11.7124%; transform: translate(0px, 0px);"></div>
            </div>
        </div>
        <div class="os-scrollbar-corner"></div>
    </div>
    <!-- /.sidebar -->
</aside>